### ISSUE TITLE
The theme needs more colors

### ISSUE THREAD

**Issue by guilhermerodz** [guilhermerodz/veist-theme#7]
There aren't enough colors for each scope. Should we add more colors or simply reuse the existant ones?

**Comment by ermesonqueiroz** [comment]
The theme colors are beautiful, I think just reusing them is enough.

**Comment by guilhermerodz** [comment]
> The theme colors are beautiful, I think just reusing them is enough.

That's what I thought initially.

<details>
</details>


<img width="772" alt="image" src="https://user-images.githubusercontent.com/10366880/200177284-90c23bac-3250-4177-bd22-e818107604af.png">

**Comment by guilhermerodz** [comment]
> The theme colors are beautiful, I think just reusing them is enough.

That's what I thought initially. Perhaps we do have enough colors on our [README.md](https://github.com/guilhermerodz/veist-theme/blob/master/README.md), but those aren't being applied to the implementation (just yet). So that's our n.1 priority.

Let's compare it to `VSCode Dark+`. You'll notice `Veist` lacks a lot of semantic cases 👇🏻

<details>
<summary>VSCode Dark+ Theme (7 colors on this code 👍🏻)</summary>
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/10366880/200177605-9d9f0ddc-1ab1-4062-bd78-95ef14364246.png">
</details>

<details>
<summary>Current Veist implementation (4 colors only 👎🏻)</summary>
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/10366880/200177617-5fa4000b-bcd9-41c6-9a35-9e957f19e253.png">
</details>

After fully implementing our color palette, if it's still not enough, then we can start thinking of inheriting/deriving our palette colors to generate similar ones just to cover edge cases for a few scopes.

PS: Whatever happens, we shouldn't match colors 1:1 to the Vercel website. The goal is to polish & refine the color scheme.

<details>
<summary>Take this official example from their <a target="_blank" rel="noopener noreferrer" href="https://vercel.com/docs/beginner-sveltekit/reactivity#reactive-statements">Beginner Svelte Course</a>. The red isn't polished and we shouldn't use that.</summary>

<img width="777" alt="image" src="https://user-images.githubusercontent.com/10366880/200178132-c7668a7f-6b51-4d3e-9147-a95aa2dee48c.png">
</details>

**Comment by guilhermerodz** [comment]
However, "theme needs more colors" doesn't describe the issue. Let's continue on #9

**Comment by guilhermerodz** [comment]
However, "theme needs more colors" doesn't describe the issue. Let's continue on #9
